### ISSUE TITLE
Bug: Class Property is missing at child level

### ISSUE THREAD

**Issue by supminn** [koustov/json-graphql-parser#3]
The documentation mentions as follows
![image](https://user-images.githubusercontent.com/30731236/193463232-1b7fa5e2-2acf-407b-b8f6-ec8ae1e14301.png)
However, [Schema](https://github.com/koustov/json-graphql-parser/blob/main/templates/base-template_schema.js#L45) misses out on adding `class` property within `conditions`

**Comment by supminn** [comment]
HI @koustov 
I went through CONTRIBUTING.MD file. It has been mentioned to run `npm test`
However, I observe that test has not been setup on `package.json`

Could you please guide me on how to run this locally. I would like to attempt on fixing this issue.

**Comment by koustov** [comment]
> HI @koustov I went through CONTRIBUTING.MD file. It has been mentioned to run `npm test` However, I observe that test has not been setup on `package.json`
> 
> Could you please guide me on how to run this locally. I would like to attempt on fixing this issue.

Hello @supminn ,
Thanks for the issue. I am working on improving the readme and expected to complete by EOD today. Will update you on the same and then you can take up this issue.
I will also be tagging this issue with hactoberfest

**Comment by supminn** [comment]
> > HI @koustov I went through CONTRIBUTING.MD file. It has been mentioned to run `npm test` However, I observe that test has not been setup on `package.json`
> > Could you please guide me on how to run this locally. I would like to attempt on fixing this issue.
> 
> Hello @supminn , Thanks for the issue. I am working on improving the readme and expected to complete by EOD today. Will update you on the same and then you can take up this issue. I will also be tagging this issue with hactoberfest ANd regarding `npm test`. Its not there as of today, will create an issue for it.

Sure @koustov, Thanks.
- I have got #4 raised which covers both #3 and #5. 
- I have tested them out locally with example payloads added to the repo.
- Please review it and let me know your feedback.

**Comment by koustov** [comment]
PR merged
