### ISSUE TITLE
Bug: Clause property is missing at child level

### ISSUE THREAD

**Issue by supminn** [koustov/json-graphql-parser#5]
The documentation mentions as follows
![image](https://user-images.githubusercontent.com/30731236/193463232-1b7fa5e2-2acf-407b-b8f6-ec8ae1e14301.png)
However, [Schema](https://github.com/koustov/json-graphql-parser/blob/main/templates/base-template_schema.js#L45) misses out on adding `clause` property within `conditions`.

**Comment by koustov** [comment]
PR merged
